#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source $basedir/../bin/common.sh

#function requires_cakephp2_pear() {
#    [ $(jq --raw-output '.require["pear-pear.cakephp.org/CakePHP"]' < "$BUILD_DIR/composer.json") != "null" ]
#}


case "$1" in
    detect)
        if [ ! -f "$BUILD_DIR/update.sh" ]; then
            exit 1
        fi

        if true; then # requires_cakephp2_pear || requires_cakephp2_composer || sets_framework_cakephp2; then
            echo "-----> Detected Agile Toolkit App"
            exit 0
        else
            exit 1
        fi
        ;;
    get-log-files)
        echo "$BUILD_DIR/logs/am3_error_log" "$BUILD_DIR/logs/am3_info_log" "$BUILD_DIR/logs/am3_debug_log"
        ;;
    compile)
        echo "-----> Setting up Agile Toolkit app"
        cp "$basedir/../conf/nginx/atk4.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        ( cd "$BUILD_DIR"; ./update.sh )
        ;;
esac
